#!/usr/bin/env bash
# shellcheck disable=SC2175
set -eo pipefail

version="0.0.3"

star='\033[33m★\033[m'
left='\033[32m／\033[m'
right='\033[32m＼\033[m'
bottom='\033[32m^\033[m'
trunk='\033[31m| |\033[m'

_help() {
  echo "
${0##*/} -- Plant X'mas tree(s)

Usage: ${0##*/} [options]

Options:
 -s, --size <POSITIVE INT>    game level (default=5)
 -n, --number <POSITIVE INT>  number of tree (default=1)
 -l, --line <POSITIVE INT>    number of line (default=1)
 -a, --animation              enable animation
 -i, --interval <NATURAL INT> animation interval (default=1)
 -m, --monochrome             disable color
 -h, --help     display this help and exit
 -v, --version  output version infromation and exit

Version:
 $version"
}

_orand() {
  colors=(21 33 34 35 36 37)
  ornaments=(
    ' ' ' ' ' ' ' ' ' '
    ' ' ' ' ' ' ' ' ' '
    'i' '⸛' '⁂' '⸮' '&' '@' '｡'
  )
  echo -ne "\033[${colors[RANDOM % 6]}m${ornaments[RANDOM % 17]}\033[m"
}

_nchar() {
  local i
  if [ "$1" = 0 ]; then
    echo -n ""
  else
    for i in $(eval echo {1.."$1"}); do
      echo -ne "$2"
    done
  fi
}

_mktree() {
  local n i _
  n="$1"
  # header
  _nchar "$((n + 1))" " "
  echo -ne "$star"
  _nchar "$((n + 1))" " "
  echo

  # body
  for i in $(eval echo {1.."$n"}); do
    _nchar "$((n - i))" " "
    echo -ne "$left"
    e="$((i * 2 - 1))"
    for _ in $(eval echo {1.."$e"}); do
      _orand
    done

    echo -ne "$right"
    _nchar "$((n + 1 - i))" " "
    echo
  done

  # footer 1
  _nchar "$n" "$bottom"
  echo -ne "$trunk"
  _nchar "$n" "$bottom"
  echo

  # footer 2
  _nchar "$n" " "
  echo -ne "$trunk"
  echo
}

_print_tree() {
  eval paste "$(
    for i in $(eval echo {1.."$2"}); do
      echo -n "<(_mktree \"$1\") "
    done
  )"
}

_mono() {
  if [ "$1" = 1 ]; then
    sed 's/\x1b\[[0-9;]*m//g'
  else
    cat
  fi

}

main() {
  local size number line animation interval monochrome
  size="5"
  number="1"
  line="1"
  animation="0"
  interval="1"
  monochrome="0"
  s="0"
  for arg in "${@}"; do
    if [ $s -gt 0 ]; then
      ((s--))
      continue
    fi
    case $arg in
      -h | --help)
        _help
        return 0
        ;;
      -v | --version)
        echo "$version"
        return 0
        ;;
      -s | --size)
        if [[ -z $2 ]] || [[ $2 =~ ^-+ ]] || [ "$2" -lt 1 ]; then
          echo "error: option '$1' requires positive int -- $2" >&2
          return 1
        fi
        size="$2"
        shift 2
        s=1
        ;;
      -n | --number)
        if [[ -z $2 ]] || ! [[ $2 =~ ^[0-9]+$ ]] || [ "$2" -lt 1 ]; then
          echo "error: option '$1' requires positive int -- $2" >&2
          return 1
        fi
        number="$2"
        shift 2
        s=1
        ;;
      -l | --line)
        if [[ -z $2 ]] || ! [[ $2 =~ ^[0-9]+$ ]] || [ "$2" -lt 1 ]; then
          echo "error: option '$1' requires positive int -- $2" >&2
          return 1
        fi
        line="$2"
        shift 2
        s=1
        ;;
      -i | --interval)
        if [[ -z $2 ]] || ! [[ $2 =~ ^[0-9]+$ ]] || [ "$2" -lt 0 ]; then
          echo "error: option '$1' requires natural int -- $2" >&2
          return 1
        fi
        interval="$2"
        shift 2
        s=1
        ;;
      -a | --animation)
        animation="1"
        shift
        ;;
      -m | --monochrome)
        monochrome="1"
        shift
        ;;
      -*)
        echo "error: unknown option -- $1" >&2
        return 1
        ;;
      *)
        echo "error: extra argument -- '$arg'" >&2
        return 1
        ;;
    esac
  done
  if [ "$animation" = "1" ]; then
    while :; do
      for i in $(eval echo {1.."$line"}); do
        _print_tree "$size" "$number" | _mono "$monochrome"
      done
      sleep "$interval"s
      for i in $(eval echo {1.."$line"}); do
        echo -ne "\\033[$((size + 3))A"
      done
    done
  else
    for i in $(eval echo {1.."$line"}); do
      _print_tree "$size" "$number" | _mono "$monochrome"
    done
  fi
}

main "${@}"
exit $?
